[build]
  command = "npm install && npm run test && npm run build"
  publish = "dist/tic-tac-toe/browser"

[build.environment]
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-copy"

[plugins.inputs]
  from = "tests/units.html"
  to = "dist/tic-tac-toe/tests/units.html"